apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: davor-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
        - name: frontend
          image: davordavor/nextjs-classifieds-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: "postgresql://davor_user:davor_password@postgres-service:5432/oglasi_db"
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_ENV
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_PORT