apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: davor-namespace
type: Opaque
stringData:
  POSTGRES_USER: "davor_user"
  POSTGRES_PASSWORD: "davor_password"
  POSTGRES_DB: "oglasi_db"